package inventory.model;
// Generated Aug 2, 2020 5:41:10 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * ProductInStock generated by hbm2java
 */
public class ProductInStock implements java.io.Serializable {

	private Integer id;
	private ProductInfo productInfo;
	private int qty;
	private int activeFlag;
	private Date createddate;
	private Date updateddate;

	public ProductInStock() {
	}

	public ProductInStock(ProductInfo productInfo, int qty, int activeFlag, Date createddate, Date updateddate) {
		this.productInfo = productInfo;
		this.qty = qty;
		this.activeFlag = activeFlag;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductInfo getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(ProductInfo productInfo) {
		this.productInfo = productInfo;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
