package inventory.model;
// Generated Aug 2, 2020 5:41:10 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.web.multipart.MultipartFile;

/**
 * ProductInfo generated by hbm2java
 */
public class ProductInfo implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private String code;
	private String description;
	private String imageUrl;
	private int activeFlag;
	private Date createddate;
	private Date updateddate;
	private Set invoices = new HashSet(0);
	private Set productInStocks = new HashSet(0);
	private Set histories = new HashSet(0);
	private MultipartFile multipartFile;
	private Integer cateId;
	
	public ProductInfo() {
	}

	public ProductInfo(Category category, String name, String code, String imageUrl, int activeFlag, Date createddate,
			Date updateddate) {
		this.category = category;
		this.name = name;
		this.code = code;
		this.imageUrl = imageUrl;
		this.activeFlag = activeFlag;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	public ProductInfo(Category category, String name, String code, String description, String imageUrl, int activeFlag,
			Date createddate, Date updateddate, Set invoices, Set productInStocks, Set histories) {
		this.category = category;
		this.name = name;
		this.code = code;
		this.description = description;
		this.imageUrl = imageUrl;
		this.activeFlag = activeFlag;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.invoices = invoices;
		this.productInStocks = productInStocks;
		this.histories = histories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

	public Set getProductInStocks() {
		return this.productInStocks;
	}

	public void setProductInStocks(Set productInStocks) {
		this.productInStocks = productInStocks;
	}

	public Set getHistories() {
		return this.histories;
	}

	public void setHistories(Set histories) {
		this.histories = histories;
	}

	public MultipartFile getMultipartFile() {
		return multipartFile;
	}

	public void setMultipartFile(MultipartFile multipartFile) {
		this.multipartFile = multipartFile;
	}
	
	public Integer getCateId() {
		return cateId;
	}

	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}
}
