package inventory.model;
// Generated Aug 2, 2020 5:41:10 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String email;
	private String fullname;
	private int activeFlag;
	private Date createddate;
	private Date updateddate;
	private Set userRoles = new HashSet(0);

	public Users() {
	}

	public Users(String username, String password, String fullname, int activeFlag, Date createddate,
			Date updateddate) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.activeFlag = activeFlag;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	public Users(String username, String password, String email, String fullname, int activeFlag, Date createddate,
			Date updateddate, Set userRoles) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.fullname = fullname;
		this.activeFlag = activeFlag;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.userRoles = userRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
